"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DefaultLogger = void 0;
var picocolors_1 = require("picocolors");
var vendure_logger_1 = require("./vendure-logger");
var DEFAULT_CONTEXT = 'Vendure Server';
/**
 * @description
 * The default logger, which logs to the console (stdout) with optional timestamps. Since this logger is part of the
 * default Vendure configuration, you do not need to specify it explicitly in your server config. You would only need
 * to specify it if you wish to change the log level (which defaults to `LogLevel.Info`) or remove the timestamp.
 *
 * @example
 * ```ts
 * import { DefaultLogger, LogLevel, VendureConfig } from '\@vendure/core';
 *
 * export config: VendureConfig = {
 *     // ...
 *     logger: new DefaultLogger({ level: LogLevel.Debug, timestamp: false }),
 * }
 * ```
 *
 * @docsCategory Logger
 */
var DefaultLogger = /** @class */ (function () {
    function DefaultLogger(options) {
        /** @internal */
        this.level = vendure_logger_1.LogLevel.Info;
        this.defaultContext = DEFAULT_CONTEXT;
        this.localeStringOptions = {
            year: '2-digit',
            hour: 'numeric',
            minute: 'numeric',
            day: 'numeric',
            month: 'numeric',
        };
        this.level = options && options.level != null ? options.level : vendure_logger_1.LogLevel.Info;
        this.timestamp = options && options.timestamp !== undefined ? options.timestamp : true;
    }
    /**
     * @description
     * A work-around to hide the info-level logs generated by Nest when bootstrapping the AppModule.
     * To be run directly before the `NestFactory.create()` call in the `bootstrap()` function.
     *
     * See https://github.com/nestjs/nest/issues/1838
     * @internal
     */
    DefaultLogger.hideNestBoostrapLogs = function () {
        var logger = vendure_logger_1.Logger.logger;
        if (logger instanceof DefaultLogger) {
            if (logger.level === vendure_logger_1.LogLevel.Info) {
                this.originalLogLevel = vendure_logger_1.LogLevel.Info;
                logger.level = vendure_logger_1.LogLevel.Warn;
            }
        }
    };
    /**
     * @description
     * If the log level was changed by `hideNestBoostrapLogs()`, this method will restore the
     * original log level. To be run directly after the `NestFactory.create()` call in the
     * `bootstrap()` function.
     *
     * See https://github.com/nestjs/nest/issues/1838
     * @internal
     */
    DefaultLogger.restoreOriginalLogLevel = function () {
        var logger = vendure_logger_1.Logger.logger;
        if (logger instanceof DefaultLogger && DefaultLogger.originalLogLevel !== undefined) {
            logger.level = DefaultLogger.originalLogLevel;
        }
    };
    DefaultLogger.prototype.setDefaultContext = function (defaultContext) {
        this.defaultContext = defaultContext;
    };
    DefaultLogger.prototype.error = function (message, context, trace) {
        if (context === 'ExceptionsHandler' && this.level < vendure_logger_1.LogLevel.Verbose) {
            // In Nest v7, there is an ExternalExceptionFilter which catches *all*
            // errors and logs them, no matter the LogLevel attached to the error.
            // This results in overly-noisy logger output (e.g. a failed login attempt
            // will log a full stack trace). This check means we only let it log if
            // we are in Verbose or Debug mode.
            return;
        }
        if (this.level >= vendure_logger_1.LogLevel.Error) {
            this.logMessage(picocolors_1.default.red('error'), picocolors_1.default.red(this.ensureString(message) + (trace ? "\n".concat(trace) : '')), context);
        }
    };
    DefaultLogger.prototype.warn = function (message, context) {
        if (this.level >= vendure_logger_1.LogLevel.Warn) {
            this.logMessage(picocolors_1.default.yellow('warn'), picocolors_1.default.yellow(this.ensureString(message)), context);
        }
    };
    DefaultLogger.prototype.info = function (message, context) {
        if (this.level >= vendure_logger_1.LogLevel.Info) {
            this.logMessage(picocolors_1.default.blue('info'), this.ensureString(message), context);
        }
    };
    DefaultLogger.prototype.verbose = function (message, context) {
        if (this.level >= vendure_logger_1.LogLevel.Verbose) {
            this.logMessage(picocolors_1.default.magenta('verbose'), this.ensureString(message), context);
        }
    };
    DefaultLogger.prototype.debug = function (message, context) {
        if (this.level >= vendure_logger_1.LogLevel.Debug) {
            this.logMessage(picocolors_1.default.magenta('debug'), this.ensureString(message), context);
        }
    };
    DefaultLogger.prototype.logMessage = function (prefix, message, context) {
        process.stdout.write([prefix, this.logTimestamp(), this.logContext(context), message, '\n'].join(' '));
    };
    DefaultLogger.prototype.logContext = function (context) {
        return picocolors_1.default.cyan("[".concat(context || this.defaultContext, "]"));
    };
    DefaultLogger.prototype.logTimestamp = function () {
        if (this.timestamp) {
            var timestamp = new Date(Date.now()).toLocaleString(undefined, this.localeStringOptions);
            return picocolors_1.default.gray(timestamp + ' -');
        }
        else {
            return '';
        }
    };
    DefaultLogger.prototype.ensureString = function (message) {
        return typeof message === 'string' ? message : JSON.stringify(message, null, 2);
    };
    return DefaultLogger;
}());
exports.DefaultLogger = DefaultLogger;
